language: node_js

node_js:
  - 10

cache:
  directories:
    - ~/.npm
    - ~/.cache
    - node_modules
    - tests/e2e/project/node_modules

install:
  - npm install
  - cd tests/e2e/project && npm install
  - cd -

script:
  - cd test/e2e/project
  # this is not necessary for the e2e test but we make sur build and generate works
  - npm run generate
  # this is the dev version that is tested
  - npm run dev &
  - cd -
  - npm run e2e
