language: node_js

node_js:
  - 10

cache:
  directories:
    - ~/.npm
    - ~/.cache
    - node_modules
    - tests/e2e/project/node_modules

install:
  - npm install
  - cd tests/e2e/project && npm install
  - cd -

script: ./tests.sh
